# -*- coding: utf-8 -*-
"""practice150725.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16ZOBoT_SAVHMbJWZqDuk2rhcXfdh54ey
"""

import math
import statistics
import numpy as np
import pandas as pd
from scipy import linalg

print("floor value of 1.7 is",math.floor(1.7))

print("ceil value of 1.7 is",math.ceil(1.7))

print("Square root of 49 is",math.sqrt(49))
print("Integer square root of 49 is",math.isqrt(49))

print("GCD of 6 and 4 is",math.gcd(6,4))

arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print("Dimensions of the array:",arr.ndim)
print("Shape of the array:",arr.shape)
print("Size of the array:",arr.size)
print("Sum:",arr.sum())
print("Mean:",arr.mean())
arr2=np.array([[5,21,3],[8,1,7]])
print("Sorted array:",np.sort(arr2))
print("Sine of array elements",np.sin(arr))

mat=np.array([[2,3,4],[1,6,5],[7,8,9]])
print(mat)
determinant=linalg.det(mat)
print(determinant)
eigenval,eigenvect=linalg.eig(mat)
print("EigenValues:",eigenval)
print("EigenVectors:",eigenvect)

l=list(range(1,31))
print("List as list\n:",l)
print("List converted to a 1D array\n",np.array(l))
print("List converted to a 2D array\n",np.array(l).reshape(5,6))
print("List converted to 3D array\n",np.array(l).reshape(2,5,3))

zero_matrix=np.zeros(3)
print("Zeroes Matrix ->",zero_matrix)
ones_matrix=np.ones(4)
print("Ones matrix ->",ones_matrix)
identity_matrix=np.eye(4)
print("Identity Matrix ->\n",identity_matrix)
random_matrix=np.random.rand(3,3)
print("Random matrix\n",random_matrix)

data=[1,2,3,4,5,6]
df=pd.Series(data)
print(df)
print("Index:",df.index)
print("Values:",df.values)
arr=np.array([1,2,3,4,5,6])
print("Series:",df)
print("NumPy array:",arr)
index=['a','b','c','d','e','f']
data2=["apple","banana","cherry","dragonfruit","elephant","fruit"]
series=pd.Series(data2,index=index)
print(series)
df2=pd.Series(arr,index=index)
print("Series with index\n",df2)
print("Accessing valuews in a series:")
print("Value at index a:",series['a'])

df3=pd.DataFrame({
    'Name':['Rathina','Gowry','Manohari'],
    'Age':[19,20,23],
    'City':['Bangalore','Chennai','Mumbai']
})
print("DataSet created using pandas\n",df3)

url="https://people.sc.fsu.edu/~jburkardt/data/csv/hw_200.csv"
df4=pd.read_csv(url)
print("Dataset using csv\n",df4.head())



from sklearn import datasets
url=datasets.load_iris()
df5=pd.DataFrame(url.data,columns=url.feature_names)
print("Dataset using sklearn\n",df5.head())

import pandas as pd
import matplotlib.pyplot as plt
#data=[1,2,3,4,5,6]
x=[1,3,5,7,9]
y=[2,4,6,8,10]
plt.plot(x,y,label="Line",color="blue",marker="o")
plt.title("Line")
plt.xlabel("X axis")
plt.ylabel("Y axis")
plt.legend()
plt.show()